services:
  svl-db:
    image: postgres:16
    container_name: svl-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - svl_db_data:/var/lib/postgresql/data

  svl-api:
    build: ./api
    container_name: svl-api
    environment:
      DB_HOST: svl-db
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASS: apppass
    ports:
      - "8000:8000"
    depends_on:
      - svl-db

  svl-frontend:
    build: ./frontend
    container_name: svl-frontend
    ports:
      - "8081:80"

volumes:
  svl_db_data:
