apiVersion: v1
kind: Secret
metadata:
  name: svl-db-secret
  namespace: svl
type: Opaque
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svl-db-pvc
  namespace: svl
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svl-db
  namespace: svl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svl-db
  template:
    metadata:
      labels:
        app: svl-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: svl-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: svl-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: svl-db
  namespace: svl
spec:
  selector:
    app: svl-db
  ports:
    - port: 5432
      targetPort: 5432
